apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wemixfi-backend.fullname" $ }}-initializer-mysql
  labels:
    {{- include "wemixfi-backend.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "wemixfi-backend.labels" $ | nindent 8 }}
    spec:
      restartPolicy: "Never"
      serviceAccountName: {{ include "wemixfi-backend.serviceAccountName" . }}
      initContainers:
      - name: {{ include "wemixfi-backend.fullname" $ }}-initializer-check-mysql-done
        image: "bitnami/kubectl:1.26.10"
        command: ["sh", "-c", "kubectl wait --timeout=300s --for=condition=Ready pod/{{ template "mysql.primary.fullname" .Subcharts.mysql }}-0"]
      containers:
      - name: {{ include "wemixfi-backend.fullname" $ }}-initializer-mysql
        image: "{{ $.Values.scheduler.mysql.image }}:{{ $.Values.scheduler.tag }}"
        command: ["node", "./bin/initialize.js"]
        envFrom:
          - configMapRef:
              name: {{ include "wemixfi-backend.fullname" $ }}-common-configmap
        
  completions: 1
  podFailurePolicy:
    rules:
    - action: FailJob
      onExitCodes:
        containerName: {{ include "wemixfi-backend.fullname" $ }}-initializer-mysql
        operator: NotIn
        values: [0]
