# Default values for wemix-fi-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

strategy:
  type: RollingUpdate

image:
  registry: docker.io
  repository: junius06
  pullPolicy: Always
  tag: "dev"

imagePullSecrets: 
  - name: docker-registry
nameOverride: ""
fullnameOverride: ""

applications:
  api:
    replicaCount: 3
    ports:
      - name: "api-svc"
        containerPort: 8080
        protocol: TCP
    service: 
      type: LoadBalancer
    command: [ 'sh', '-c' ]
    args: [ 'source /vault/secrets/env && node ./bin/api.js' ]

  mysqlData:
    replicaCount: 1
    command: [ 'sh', '-c' ]
    args: [ 'source /vault/secrets/env && node ./bin/range.target.js' ]
    list:
      - one
      - two
      - three
      - four
      - five
      - fix
      - seven

  redisData: 
    replicaCount: 1
    command: [ 'sh', '-c' ]
    args: [ 'source /vault/secrets/env && node ./bin/instance.js' ]

  influxData:
    replicaCount: 1
    command: [ 'sh', '-c' ]
    list: 
      - command01
      - command02
      - command03
      - command04
      - command05
      - command06
      - command07
      - command08

probe:
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    
  customStartupProbe: {}
  
  customLivenessProbe: {}
  
  customReadinessProbe: {}

#########################################################

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
