apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-api.serviceName" . }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api_server.service.type }}
  {{- with .Values.api_server.service.ports }}
  ports: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "backend-api.selectorLabels" . | nindent 4 }}
