apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "project-backend.serviceAccountName" . }}-role
  labels:
    {{- include "project-backend.labels" . | nindent 4 }}
rules:
- apiGroups: ["", "batch", "apps"]
  resources:
  - pods
  - jobs
  - statefulsets
  verbs:
  - get
  - watch
  - list